//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SqliteVisualizer {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SqliteVisualizer.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visualizer does not support DMP debugging.
        /// </summary>
        internal static string ErrMsg_DmpDebuggingNotSupported {
            get {
                return ResourceManager.GetString("ErrMsg_DmpDebuggingNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failure getting tables: {0}.
        /// </summary>
        internal static string ErrMsg_FailureGettingTables {
            get {
                return ResourceManager.GetString("ErrMsg_FailureGettingTables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A required function evaluation failed.
        /// </summary>
        internal static string ErrMsg_FuncEvalFailed {
            get {
                return ResourceManager.GetString("ErrMsg_FuncEvalFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No tables found.
        /// </summary>
        internal static string ErrMsg_NoTablesFound {
            get {
                return ResourceManager.GetString("ErrMsg_NoTablesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initial function evaluation for query has failed.
        /// </summary>
        internal static string ErrMsg_PrepareFailed {
            get {
                return ResourceManager.GetString("ErrMsg_PrepareFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visualizer has encountered an error. No further evaluations are possible.
        ///
        ///Please close the visualizer.
        ///
        ///{0}: {1}.
        /// </summary>
        internal static string ErrMsg_VisualizerFailure {
            get {
                return ResourceManager.GetString("ErrMsg_VisualizerFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting rows....
        /// </summary>
        internal static string Msg_GettingRows {
            get {
                return ResourceManager.GetString("Msg_GettingRows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading tables....
        /// </summary>
        internal static string Msg_LoadingTables {
            get {
                return ResourceManager.GetString("Msg_LoadingTables", resourceCulture);
            }
        }
    }
}
