//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Samples.VisualStudio.CodeSweep.VSPackage.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Samples.VisualStudio.CodeSweep.VSPackage.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Term Table.
        /// </summary>
        internal static string AddTableDialogCaption {
            get {
                return ResourceManager.GetString("AddTableDialogCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The project already has a CodeSweep configuration..
        /// </summary>
        internal static string AlreadyHasConfiguration {
            get {
                return ResourceManager.GetString("AlreadyHasConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The background scanner cannot be started because it is already running..
        /// </summary>
        internal static string AlreadyScanning {
            get {
                return ResourceManager.GetString("AlreadyScanning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CodeSweep.
        /// </summary>
        internal static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The background scanner cannot be started because it is already running..
        /// </summary>
        internal static string BackgroundScanAlreadyRunning {
            get {
                return ResourceManager.GetString("BackgroundScanAlreadyRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class.
        /// </summary>
        internal static string ClassColumn {
            get {
                return ResourceManager.GetString("ClassColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        internal static string CommentColumn {
            get {
                return ResourceManager.GetString("CommentColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The property name cannot be empty..
        /// </summary>
        internal static string EmptyProperty {
            get {
                return ResourceManager.GetString("EmptyProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string FileColumn {
            get {
                return ResourceManager.GetString("FileColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: could not open CodeSweep term table specified: {0}.
        /// </summary>
        internal static string FileNotScannedError {
            get {
                return ResourceManager.GetString("FileNotScannedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CodeSweep Term Table (*.xml)|*.xml|All Files(*.*)|*.*.
        /// </summary>
        internal static string FileOpenDlgFilters {
            get {
                return ResourceManager.GetString("FileOpenDlgFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High.
        /// </summary>
        internal static string HighPriority {
            get {
                return ResourceManager.GetString("HighPriority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CodeSweep Configurations Not Equal.
        /// </summary>
        internal static string InconsistentConfigurationCaption {
            get {
                return ResourceManager.GetString("InconsistentConfigurationCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CodeSweep could not be opened because the selected projects do not have identical CodeSweep configurations..
        /// </summary>
        internal static string InconsistentConfigurationError {
            get {
                return ResourceManager.GetString("InconsistentConfigurationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Term Table.
        /// </summary>
        internal static string InvalidTermTableCaption {
            get {
                return ResourceManager.GetString("InvalidTermTableCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified term table does not match the term table XML schema.  Please select another file..
        /// </summary>
        internal static string InvalidTermTableError {
            get {
                return ResourceManager.GetString("InvalidTermTableError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line.
        /// </summary>
        internal static string LineColumn {
            get {
                return ResourceManager.GetString("LineColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low.
        /// </summary>
        internal static string LowPriority {
            get {
                return ResourceManager.GetString("LowPriority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium.
        /// </summary>
        internal static string MediumPriority {
            get {
                return ResourceManager.GetString("MediumPriority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build integration enabled only for projects that use MSBuild.
        /// </summary>
        internal static string NonMSBuildCheckboxTip {
            get {
                return ResourceManager.GetString("NonMSBuildCheckboxTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no previous background scan to repeat..
        /// </summary>
        internal static string NoPreviousScan {
            get {
                return ResourceManager.GetString("NoPreviousScan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap priority {
            get {
                object obj = ResourceManager.GetObject("priority", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Priority.
        /// </summary>
        internal static string PriorityColumn {
            get {
                return ResourceManager.GetString("PriorityColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Priority Number.
        /// </summary>
        internal static string PriorityNumberColumn {
            get {
                return ResourceManager.GetString("PriorityNumberColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project.
        /// </summary>
        internal static string ProjectColumn {
            get {
                return ResourceManager.GetString("ProjectColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replacement.
        /// </summary>
        internal static string ReplacementColumn {
            get {
                return ResourceManager.GetString("ReplacementColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RunWithBuild cannot be set for non-MSBuild projects..
        /// </summary>
        internal static string RunWithBuildForNonMSBuild {
            get {
                return ResourceManager.GetString("RunWithBuildForNonMSBuild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Term.
        /// </summary>
        internal static string TermColumn {
            get {
                return ResourceManager.GetString("TermColumn", resourceCulture);
            }
        }
    }
}
