//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Samples.VisualStudio.CodeSweep.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Samples.VisualStudio.CodeSweep.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too many &apos;..&apos; specified in relative path..
        /// </summary>
        internal static string BackTooFar {
            get {
                return ResourceManager.GetString("BackTooFar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The base folder must be a rooted path..
        /// </summary>
        internal static string BaseFolderMustBeRooted {
            get {
                return ResourceManager.GetString("BaseFolderMustBeRooted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Both arguments to RelativizePath must be rooted..
        /// </summary>
        internal static string BothMustBeRooted {
            get {
                return ResourceManager.GetString("BothMustBeRooted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Both arguments must have the same root..
        /// </summary>
        internal static string BothMustHaveSameRoot {
            get {
                return ResourceManager.GetString("BothMustHaveSameRoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The path is not relative..
        /// </summary>
        internal static string PathNotRelative {
            get {
                return ResourceManager.GetString("PathNotRelative", resourceCulture);
            }
        }
    }
}
